---
- name: Template limits.conf
  template: src=limits.conf dest=/etc/security/limits.d/{{ limits_file_name }} owner={{ limits_user }} group={{ limits_group }} mode={{ limits_chmod }} backup=yes
  when: limits_run_task
  register: limitstemplates

- name: Template sysctl.conf
  template: src=sysctl.conf dest=/etc/sysctl.d/{{ sysctl_file_name }} owner={{ sysctl_user }} group={{ sysctl_group }} mode={{ sysctl_chmod }} backup=yes
  when: sysctl_run_task
  register: sysctltemplates

- name: Reload sysctl settings
  command: sysctl -p
  when: sysctl_reload and sysctl_run_task and sysctltemplates.changed

- name: Reload sysctl settings with system flag
  command: sysctl --system
  when: sysctl_reload and sysctl_run_task and sysctltemplates.changed

- name: Ensure PAM entries
  lineinfile: >
    dest=/etc/pam.d/{{ item }} regexp='session[\s]+required[\s]+pam_limits.so'
    line='session required pam_limits.so' state=present
  with_items:
    - "{{ pam_files_to_check }}"
  when: pam_run_task
